project:
  type: website
  output-dir: docs

website:
  title: "Inferential Statistics"
  sidebar:
    background: primary
    logo: "images/ggplot2.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Zahedasghar
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: https://discord.com/channels/1209036560503279616/1209036560503279619
        text: Forum

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

